account_app/urls.py
from django.urls import path, re_path
from . import views

app_name = "account_app"

urlpatterns = [
    path('signup/', views.signup_view, name = "signup"),
    path('login/', views.login_view, name = "login"),
    path('logout/', views.logout_view, name = "logout"),
]

article_app/urls.py
from django.urls import path, re_path
from . import views as view_article

app_name = 'article_app' # namespace for url's name

urlpatterns = [
    path('', view_article.list_article, name = 'list'),
    path('create/', view_article.create_article, name = 'create'),
    re_path(r'^(?P<slug>[\w-]+)/$', view_article.details, name = 'details'),
]

djangonautic/urls.py
from django.contrib import admin
from django.urls import path, include
from article_app import views as view_article

from django.contrib.staticfiles.urls import staticfiles_urlpatterns # add by spd for accessing static files
from django.conf.urls.static import static # add by spd for accessing media files
from django.conf import settings # add by spd for accessing media files

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article_app.urls')),
    path('account/', include('account_app.urls')),
    path('', view_article.list_article, name = "home"),
]

urlpatterns += staticfiles_urlpatterns() # add by spd for accessing static files
urlpatterns += static( settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) # add by spd for accessing media files

account_app/models.py
from django.db import models

# Create your models here.

article_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100) # we also can use verbose_name
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True, verbose_name = "publishing date")
    thumb = models.ImageField(default="default.png", blank = True)

    # add in author later
    author = models.ForeignKey( User, default = None, on_delete = models.PROTECT)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + "..."

    def jkt_time(self):
        import pytz
        # jakarta_tz = pytz.timezone('Asia/Jakarta')
        jakarta_tz = pytz.timezone('Asia/Jakarta')
        # return self.date.astimezone(jakarta_tz)
        # return self.date.tzinfo
        # return self.date.astimezone(jakarta_tz).tzinfo
        jkt_time = self.date.astimezone(jakarta_tz)

        return jkt_time

article_app/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'thumb']

account_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        myform = UserCreationForm(request.POST)
        if myform.is_valid():
            user = myform.save()
            # log user in
            login( request, user)

            return redirect("article_app:list")
    else:
        myform = UserCreationForm()

    return render(request,'account/signup.html', { 'form': myform })

def login_view(request):
    if request.method == 'POST':
        myform = AuthenticationForm(data=request.POST)
        if myform.is_valid():
            # log in User
            user = myform.get_user()
            login(request, user)

            if 'next' in request.POST:
                return redirect(request.POST.get("next"))
            else:
                return redirect("article_app:list")
    else:
        myform = AuthenticationForm()

    return render(request, 'account/login.html', { 'form': myform })

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect("article_app:list")

article_app/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

from . import forms

# Create your views here.
def list_article(request):
    articles = Article.objects.all().order_by('date')
    class Tambah:
        i=0

        def get(self):
            self.i += 1
            return self.i

    tambah = Tambah()
    return render(request,'article/article_list.html', { 'article_list': articles,
    'tambah': tambah})

def details(request, slug):
    #return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(request, 'article/article_detail.html', { 'article': article })

# @login_required(login_url="/account/login/")
@login_required(login_url="account_app:login")
def create_article(request):
    if request.method == "POST":
        myform = forms.CreateArticle( request.POST, request.FILES)
        if myform.is_valid():
            # save form
            my_instance = myform.save(commit=False)
            my_instance.author = request.user
            my_instance.save()
            return redirect("article_app:list")
    else:
        myform = forms.CreateArticle()

    return render( request, 'article/article_create.html', { 'form': myform })

article_app/templates/article/article_create.html
{% extends 'kerangka.html' %}

{% block badan %}
<div class="create-article">
  <h2>Create an awesome new article</h2>
  <form class="site-form" action="{% url 'article_app:create' %}" method="post" enctype="multipart/form-data">

    {% csrf_token %}

    {{ form }}

    <button type="submit">Create</button>

  </form>
</div>

<form class="" action="index.html" method="post">
  <input type="text" name="test123" value="test">
</form>

{% load static from staticfiles %}
<script src="{% static 'js/slugify.js' %}"></script>
{% endblock %}

article_app/templates/article/article_detail.html
{% extends 'kerangka.html' %}

{% block badan %}
<div class="article_detail">
  <div class="article">
    <img src="{{ article.thumb.url }}" alt="{{ article.thumb }}">
    <h2>{{ article.title }}</h2>
    <p>{{ article.body }}</p>
    <p>{{ article.date }}</p>
    <p>{{ article.jkt_time }}</p>    
  </div>
</div>
{% endblock %}

article_app/templates/article/article_list.html
{% extends 'kerangka.html' %}

{% block badan %}
<h1>Article List :</h1>
<div class="article_list">
  {% if article_list %}
  <div class="articles">
    {% for article in article_list %}
    <div class="article">
      <h2><a href="{% url 'article_app:details' slug=article.slug %}">{{ tambah.get }}. {{ article.title }}</a></h2>
      <p>{{ article.snippet }}</p>
      <p>{{ article.date }}</p>
      <!-- https://docs.djangoproject.com/en/dev/ref/templates/builtins/#std:templatefilter-date -->
      <p>tanggal {{ article.date | date:"d-m-Y"}}, jam {{ article.date | date:"h:i:s a"}}</p>
      <p>{{ article.jkt_time }}</p>
      <p class="author">added by {{ article.author.username }}</p>
    </div>
    {% endfor %}
  </div>
  {% else %}
  There is no article.
  {% endif %}
</div>
{% endblock %}

templates/kerangka.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block judul %}Judul Halaman{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body>

    <header class="wrapper">
      <h1><a href="{% url 'home' %}"><img src="{% static 'img/logo.png' %}" alt="djangonautic"></a></h1>
      <nav>
        <ul>
          {% if user.is_authenticated %}
          <li>
            <form class="logout-link" action="{% url 'account_app:logout' %}" method="post">
              {% csrf_token %}
              <button type="submit">Logout</button>
            </form>
          </li>
          <li><a href="{% url 'article_app:create' %}" class="highlight">New Article</a></li>
          {% else %}
          <li><a href="{% url 'account_app:login' %}">Login</a></li>
          <li><a href="{% url 'account_app:signup' %}">Signup</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>

    <div class="">
      {% if request.user.username %}
      <h5>Welcome {{ request.user.username }}</h5>
      {% endif %}
    </div>

    <div class="wrapper">
      {% block badan %}
      <h1>Isi Halaman</h1>
      {% endblock %}
    </div>

  </body>
</html>